# Generated by Django 4.2.7 on 2024-01-26 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0005_alter_review_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Pet',
            new_name='pet',
        ),
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 20, 49, 51, 956347)),
        ),
    ]
