# Generated by Django 4.2.7 on 2024-01-26 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0006_rename_pet_review_pet_alter_review_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 21, 8, 36, 986695)),
        ),
    ]
