# Generated by Django 4.2.7 on 2024-01-28 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0010_alter_review_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 28, 21, 44, 53, 733224)),
        ),
    ]
