# Generated by Django 4.2.7 on 2024-02-06 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0014_alter_review_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 13, 12, 31, 967262, tzinfo=datetime.timezone.utc)),
        ),
    ]
