# Generated by Django 4.2.7 on 2024-02-06 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0015_alter_review_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
